
volumes:
  pg_data:

services:
  db:
    container_name: db
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    env_file: ./.env
#    ports:
#      - 5672:5672
#      - 15672:15672

  payments_svc:
    container_name: payments-svc
    build: ./PaymentsService
    env_file: ./.env

  orders_svc:
    container_name: orders-svc
    build: ./OrdersService
    env_file: ./.env

  gateway:
    container_name: gateway
    build: ./APIGateway
    env_file: ./.env
    ports:
      - 8080:8080
